# Site settings
title: H4X0R
email: milkey-mouse@team-ivan.com
description: > # this means to ignore newlines until "baseurl:"
  A game about what some people think hacking is
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://h4x0r.team-ivan.com/" # the base hostname & protocol for your site
twitter_username: username
github_username: milkey-mouse

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]